language: java
sudo: false
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: "gHeiUVJaUWwnBH9KNJ1ZZSVopNtyPFdXozcwg4yy3EXjFb2bdmsJk8tOyjsq654me/CT0Jnof8+goCdryUCuxlcv8yh/vFxSCgoiEzrQ02x1I2bPOg8k6DDROTMMEFQssE4UnL6bXjloQPcK7Y/1DfnEPcFmmjHxmKMvD/Gj4Z/H50x8ymxqE5cq1SjPLaJ65UNCAcsjkvbMZEE4aOHVNrteyPfvkMv6Cewp9VwhEo0Raf4l1wLjjMHDDQpfcSiz0Wjk+NRksg8C2Civ/eDAPiSmKWg7zL7kGuuwvBZLZDfIYOFrLYLBAbw5hdYlIiCJKn80xbIKgfzIz3FoIT5I8Cc+/eOd0BM5lqhzp1kMeZeG+gwzoOyDx9p/WHo6W40xjl2EGUl69K6/H8ru5UvQtFiPG3lNU+hbdZg4QbqpQ8Q/yytqk9ZHzyfydX4+xKk8tHoVNng1B2mGf2jRJA4k7IuXTz/JPFGU3AM/V3M8L7cR7YdYAFTBWktRNAPdp2vJ1uULQ42J78McFW4V/xDUFdCcZ4FCiM1u/qGcGuXedAaHsUz0HQ5L6B1TgNtSfBJRL3jSTSTxrdm2yBOZJcDzyV1eRtUr1ogP0t8u+GHKi5UEYa/876XMvvRmnojLyRODIZvTncrTVrtYw9Wn++uSd0dnv59XV7LRYAJ2FPs/BWU=" 
  app: ciexample
  on:
    repo: TheArk3stry/ci-example
